### ISSUE TITLE
Parsing data from Many to Many Field django orms

### ISSUE THREAD

**Issue by machineska** [kigawas/fastapi-django#3]
Hi.. your project sample  it is really make a high impact for me.  I'm grateful, Thank you so much.. 
I would like  to bring FastAPI and Django as orms in the same app. 
After some journey I face a problem to parsing a many to many field with the FastAPI schema. If you don't mind, would you like to teach me to do that? 

Thank you so much.

**Comment by kigawas** [comment]
Many-to-many relationship is implemented with a join table in Django, basically in this pattern:

1. Retrieve some rows in table A
2. Retrieve the intermediary rows in the join table based on A's primary key to get the PKs of data in table B
3. Retrieve the corresponding rows in table B

Pydantic's orm_mode works in most cases, if you define your pydantic models well, the only job is just to write the logic of retrieving many-to-many data.

A foreign key example is [here](https://github.com/kigawas/fastapi-django/blob/master/polls/schemas/__init__.py#L30). Many-to-many would just be similar.

**Comment by machineska** [comment]
Thanks, I solved it with just make many to many through one table extra not with django Many to Many by default.
