### ISSUE TITLE
Django App  not mounted

### ISSUE THREAD

**Issue by AbhijithGanesh** [kigawas/fastapi-django#8]
The Django App has not been mounted via asgi.py. Please resolve this issue.

**Comment by kigawas** [comment]
Did you specify the right module?

`uvicorn mysite.asgi:application --port 8001 --reload`

**Comment by AbhijithGanesh** [comment]
Yes I did

**Comment by kigawas** [comment]
How did you start the server? Can you post your command?

**Comment by AbhijithGanesh** [comment]
![image](https://user-images.githubusercontent.com/67182544/133022687-02bcb1a6-9b70-4670-af28-57b43fb2d637.png)
It either runs django or the fastapi application through asgi instead of integrating both. The API would be not accessed if not integrated(if you run a single command and you expect it to load)

**Comment by AbhijithGanesh** [comment]
![image](https://user-images.githubusercontent.com/67182544/133022814-c19d0f80-5446-46f4-b763-e7d1f24fe116.png)
In this image you can see the API loading the Open API docs.

**Comment by kigawas** [comment]
That's the expected behavior since only Django ORM is used here.
If you'd like to mount the Django application, just add `fastapp.mount("/django", application)` in the bottom of the asgi.py file.

**Comment by AbhijithGanesh** [comment]
> That's the expected behavior since only Django ORM is used here.
> If you'd like to mount the Django application, just add `fastapp.mount("/django", application)` in the bottom of the asgi.py file.

Sure thanks

**Comment by AbhijithGanesh** [comment]
Thanks for the clarification.

**Comment by kigawas** [comment]
About hosting the static files, see the pr above.
